const chargingQuery = `CREATE TABLE charging_station(id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
id_station_itinerance VARCHAR(255) NULL,
station_name VARCHAR(255) NULL,
station_implantation VARCHAR(255) NULL,
station_adress TEXT NULL,
consolidated_longitude FLOAT NULL,
consolidated_latitude FLOAT NULL,
geojson_coordinates VARCHAR(255) NULL,
nbr_poc INT NULL,
power_voltage FLOAT NULL,
free TINYINT NULL,
access_condition VARCHAR(255) NULL,
is_booked TINYINT NULL,
hourly_access VARCHAR(255) NULL,
access_prm TEXT NULL,
motor_cycle_station TINYINT NULL,
launching_date VARCHAR(255) NULL,
update_date VARCHAR(255) NULL,
datagouv_organization_or_owner TEXT NULL)`;

module.exports = chargingQuery;
